### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by rkuykendall** [adrian2x/atomic-fns#1]
I have been thinking of making a project like this for over a year. Lodash is dead and it's time to move on to something new. A few questions:

- Why name it `_` and not `noop` if `noop` is how you describe it?
- Why not go fully non-mutative? This solves the split of `lodash` and `lodash/fp` and if you look at https://github.com/lodash/lodash/issues/89 which I notice you implemented, a lot of people wanted it to be functional
- Why not link to the Github or NPM page from the docs?
- What does "MEMBER VISIBILITY" do in the docs?
- What is up with `get`? Maybe it's just not done yet?
- What do you need help on the most?

**Comment by adrian2x** [comment]
@rkuykendall Thanks for opening up with great questions! I'm considering opening separate issues for these since some of the questions are bound to take us down the rabbit hole :)

**Comment by adrian2x** [comment]
> Why name it _ and not noop if noop is how you describe it?

Agreed, and fixed.

**Comment by adrian2x** [comment]
> Why not go fully non-mutative? This solves the split of lodash and lodash/fp and if you look at https://github.com/lodash/lodash/issues/89 which I notice you implemented, a lot of people wanted it to be functional

OK, this is a big discussion. The main question is to FP or not FP. I feel like we should make this a whole separate issue so it's easy to discover the final result. But I appreciate the sentiment.

**Comment by adrian2x** [comment]
> Why not link to the Github or NPM page from the docs?
Do you mean adding it to the README, which will then show up on the docs site? When you navigate to a specific function it actually links to the source code of that file on github. But this is all auto-generated from source, so all the changes should be made on the README and we can let the tools do the rest.

> What does "MEMBER VISIBILITY" do in the docs?
Boilerplate template stuff from typedoc. I think it's meant to hide private/protected members. Maybe this can be taken out entirely as I don't see how it helps?

 > What do you need help on the most?

Testing is a great place to start. I've added a lot of tests but still not at 100% coverage. I've been using Jasmine because it's very simple to setup and test. Would also like to integrate Karma, so we can run interactive debugging sessions in the browser which would make it easier to spot bugs.

Also, adding examples to the documentation. I find that seeing a visual example is worth a lot. Like [these](https://atomic-fns.dev/functions/Functions.once.html).

**Comment by adrian2x** [comment]
> What is up with get? Maybe it's just not done yet?

It's not on parity with lodash yet. Wanna have a go at it?

**Comment by adrian2x** [comment]
Closing for now, feel free to open new issues for the other questions.
